name: Release

on: 
  workflow_call:
    tag:
      description: 'The tag to merge into'
      default: ''
      required: true
      type: string

jobs:
  release:
    name: Release @sailthru/react-scripts
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/react-scripts

    steps:
    - name: Add facebook upstream remote
      run: |
        git remote add upstream git@github.com:facebook/create-react-app.git
        git fetch upstream --tags

    - name: Checkout tagged revision
      uses: actions/checkout@${{ inputs.tag }}

    - name: Merge sailthru changes
      run: git merge sailthru

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://npm.pkg.github.com/
        scope: '@sailthru'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache yarn cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nodemodules-

    - name: Install dependencies
      if: |
        steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test --ci

    - name: Release @sailthru/react-scripts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: yarn release
